name: pr-success
on:
  pull_request: {}

jobs:
  pr-success:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Deps
        run: npm ci
      - name: Test
        run: npm test
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint
        run: npm run lint
