name: pr-success
on:
  pull_request: {}

jobs:
  pr-success:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1
      - name: Install Deps
        run: npm ci
      - name: Test
        run: npm test
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1
      - name: Lint
        run: npm run lint
