name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.ENG_GITHUB_TOKEN }}
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.ENG_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release
